# DHIMAS PRAKASA HENJO
# 2009106015
# INFORMATIKA A 2020
# POSTTEST 7 KB

In [1]:
import tensorflow as tf

# Buat Tensor (5,5) dengan nilai Random

In [3]:
random_tensor = tf.Variable(tf.random.normal([5,5], mean=4, stddev=1, dtype=tf.float32))
random_tensor.read_value().numpy()

array([[2.7853203, 3.1727605, 4.0737214, 4.0042787, 5.515864 ],
       [3.5802815, 4.410799 , 3.5650263, 3.7192261, 5.1402564],
       [4.327792 , 3.7090602, 3.0082564, 4.6721525, 3.7930858],
       [4.0673776, 3.2676263, 3.5292053, 2.8603806, 3.135638 ],
       [4.207446 , 4.9217577, 3.3506227, 6.157668 , 4.0930696]],
      dtype=float32)

In [5]:
list = [[16,18,25,34,65],[22,34,38,58,62],[15,32,73,12,43],[71,52,63,53,95],[10,24,73,46,49]]
prime_tensor = tf.convert_to_tensor(list, dtype=tf.int64).numpy()

In [6]:
print("Berikut ini adalah tampilan dimensi dari random tensor")
print(random_tensor.read_value().numpy())

print("\nBerikut ini adalah tampilan dimensi dari prime tensor")
print(prime_tensor)

Berikut ini adalah tampilan dimensi dari random tensor
[[2.7853203 3.1727605 4.0737214 4.0042787 5.515864 ]
 [3.5802815 4.410799  3.5650263 3.7192261 5.1402564]
 [4.327792  3.7090602 3.0082564 4.6721525 3.7930858]
 [4.0673776 3.2676263 3.5292053 2.8603806 3.135638 ]
 [4.207446  4.9217577 3.3506227 6.157668  4.0930696]]

Berikut ini adalah tampilan dimensi dari prime tensor
[[16 18 25 34 65]
 [22 34 38 58 62]
 [15 32 73 12 43]
 [71 52 63 53 95]
 [10 24 73 46 49]]


## Penjumlahan

In [7]:
tf.add(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[18.78532 , 21.17276 , 29.07372 , 38.00428 , 70.51586 ],
       [25.580282, 38.410797, 41.565025, 61.719227, 67.14026 ],
       [19.327793, 35.70906 , 76.008255, 16.672153, 46.793087],
       [75.067375, 55.267628, 66.529205, 55.860382, 98.135635],
       [14.207446, 28.921757, 76.350624, 52.15767 , 53.09307 ]],
      dtype=float32)>

## Pengurangan

In [8]:
tf.subtract(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-13.21468  , -14.82724  , -20.92628  , -29.995722 , -59.484135 ],
       [-18.419718 , -29.589201 , -34.434975 , -54.280773 , -56.859745 ],
       [-10.672208 , -28.29094  , -69.991745 ,  -7.3278475, -39.206913 ],
       [-66.932625 , -48.732372 , -59.470795 , -50.139618 , -91.864365 ],
       [ -5.792554 , -19.078243 , -69.649376 , -39.84233  , -44.90693  ]],
      dtype=float32)>

## Perkalian

In [9]:
tf.multiply(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 44.565125,  57.109688, 101.84303 , 136.14548 , 358.53116 ],
       [ 78.76619 , 149.96716 , 135.471   , 215.71512 , 318.6959  ],
       [ 64.916885, 118.689926, 219.60272 ,  56.06583 , 163.10269 ],
       [288.7838  , 169.91656 , 222.33994 , 151.60017 , 297.88562 ],
       [ 42.074463, 118.122185, 244.59546 , 283.25275 , 200.56041 ]],
      dtype=float32)>

## Pembagian

In [10]:
tf.divide(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0.17408252, 0.17626446, 0.16294886, 0.1177729 , 0.08485945],
       [0.16274007, 0.12972939, 0.09381648, 0.06412459, 0.08290736],
       [0.28851947, 0.11590813, 0.04120899, 0.38934603, 0.0882113 ],
       [0.05728701, 0.06283896, 0.05601913, 0.05396945, 0.03300672],
       [0.4207446 , 0.20507324, 0.04589894, 0.13386235, 0.08353204]],
      dtype=float32)>

## Logaritma

In [11]:
tf.math.log(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1.0243629, 1.154602 , 1.404557 , 1.3873634, 1.7076283],
       [1.2754414, 1.4840559, 1.2711715, 1.3135157, 1.637103 ],
       [1.4650575, 1.3107785, 1.1013607, 1.5416199, 1.33318  ],
       [1.4029984, 1.1840638, 1.2610728, 1.0509547, 1.1428326],
       [1.4368558, 1.5936657, 1.2091463, 1.8176981, 1.4092952]],
      dtype=float32)>

## Perpangkatan

In [12]:
tf.pow(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1.3122067e+07, 1.0613807e+09, 1.7773917e+15, 3.0607364e+20,
                  inf],
       [1.5352454e+12, 8.1957215e+21, 9.5144559e+20, 1.2196910e+33,
                  inf],
       [3.4994191e+09, 1.6460545e+18, 8.2600821e+34, 1.0819424e+08,
        7.8828765e+24],
       [          inf, 5.4964693e+26, 3.1889397e+34, 1.5504689e+24,
                  inf],
       [1.7385438e+06, 4.0821173e+16, 2.1585544e+38, 2.0565950e+36,
        9.7815374e+29]], dtype=float32)>

## Matmul

In [13]:
tf.matmul(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 514.9341 ,  628.9719 , 1142.5072 ,  793.56213, 1203.6108 ],
       [ 523.2651 ,  645.259  , 1126.9143 ,  853.907  , 1264.683  ],
       [ 565.6215 ,  634.2585 , 1039.9827 ,  820.4755 , 1270.339  ],
       [ 424.3473 ,  521.24176,  892.59174,  666.0031 , 1044.1106 ],
       [ 703.9823 ,  768.7261 , 1223.5356 ,  983.36017, 1508.2487 ]],
      dtype=float32)>

## ArgMAX

In [14]:
tf.argmax(random_tensor, axis=0).numpy()

array([2, 4, 0, 4, 0], dtype=int64)

## ArgMIN

In [15]:
tf.argmin(random_tensor, axis=0).numpy()

array([0, 0, 2, 3, 3], dtype=int64)

In [16]:
print(f"Size Awal : {random_tensor.shape} {prime_tensor.shape}" )

Size Awal : (5, 5) (5, 5)


In [17]:
concat_tensor_1 = tf.concat([random_tensor, prime_tensor], axis=0)
concat_tensor_2 = tf.concat([random_tensor, prime_tensor], axis=1)
print(f"Size yang sudah di concat (axis = 0) : {concat_tensor_1.shape}")
print(f"Size yang sudah di concat (axis = 1) : {concat_tensor_2.shape}")

Size yang sudah di concat (axis = 0) : (10, 5)
Size yang sudah di concat (axis = 1) : (5, 10)


## Random_tensor descending sorting

In [18]:
tf.sort(random_tensor, direction="DESCENDING").numpy()

array([[5.515864 , 4.0737214, 4.0042787, 3.1727605, 2.7853203],
       [5.1402564, 4.410799 , 3.7192261, 3.5802815, 3.5650263],
       [4.6721525, 4.327792 , 3.7930858, 3.7090602, 3.0082564],
       [4.0673776, 3.5292053, 3.2676263, 3.135638 , 2.8603806],
       [6.157668 , 4.9217577, 4.207446 , 4.0930696, 3.3506227]],
      dtype=float32)

## Random_tensor ascending sorting

In [19]:
tf.sort(random_tensor, direction="ASCENDING").numpy()

array([[2.7853203, 3.1727605, 4.0042787, 4.0737214, 5.515864 ],
       [3.5650263, 3.5802815, 3.7192261, 4.410799 , 5.1402564],
       [3.0082564, 3.7090602, 3.7930858, 4.327792 , 4.6721525],
       [2.8603806, 3.135638 , 3.2676263, 3.5292053, 4.0673776],
       [3.3506227, 4.0930696, 4.207446 , 4.9217577, 6.157668 ]],
      dtype=float32)

## Prime_tensor descending sorting

In [20]:
tf.sort(prime_tensor, direction="DESCENDING").numpy()

array([[65, 34, 25, 18, 16],
       [62, 58, 38, 34, 22],
       [73, 43, 32, 15, 12],
       [95, 71, 63, 53, 52],
       [73, 49, 46, 24, 10]], dtype=int64)

## Prime_tensor ascending sorting

In [21]:
tf.sort(prime_tensor, direction="ASCENDING").numpy()

array([[16, 18, 25, 34, 65],
       [22, 34, 38, 58, 62],
       [12, 15, 32, 43, 73],
       [52, 53, 63, 71, 95],
       [10, 24, 46, 49, 73]], dtype=int64)